#===============================================================
## home assistand informatie
#===============================================================
homeassistant:
  name: Huizebruin
  latitude: !secret latitude 
  longitude: !secret longitude 
  elevation: 10
  unit_system: metric
  time_zone: Europe/Amsterdam #Etc/GMT 
  customize: !include customize.yaml
  external_url: !secret externalurl
  internal_url: "http://192.168.178.192:8123"
  allowlist_external_dirs:
    - "/config/zigbee2mqtt"
    - "/ssl"
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#===============================================================
## Includes zodat deze lijst overzichtelijker blijft
#===============================================================
group:  !include_dir_merge_named groups/
sensor: !include_dir_merge_list sensors/
template:
  - sensor: !include_dir_merge_list template/sensor/
binary_sensor: !include_dir_merge_list binary_sensors/
switch: !include_dir_merge_list switch/
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml  
utility_meter: !include utility_meter/utility.yaml
camera: !include camera/camera.yaml
input_select: !include input-select.yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
#===============================================================
#samsung tv
#samsungtv_smart:
#  - host: !secret samsungtv_smart
#====================
#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
#====================
#google agenda    
google:
  client_id: !secret google_CLIENT_ID
  client_secret: !secret google_CLIENT_SECRET
#===============================================================
media_player:
  - platform: mpd
    host: 192.168.178.162
#===============================================================
# Text to speech
tts:
  - platform: google_translate
    language: 'nl'
    base_url: http://192.168.178.192:8123 # interne ip adres 
#===============================================================
mqtt:
  discovery: true
#===============================================================
# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
#===============================================================

## Telegram
#===============================================================
telegram_bot:
  - platform: polling
    api_key: !secret telegramkey
    allowed_chat_ids:
      -  !secret telegram_chatID
notify:
    - name: Wobbebot
      platform: telegram
      chat_id: !secret telegram_chatID

    - name: twitter wobbele
      platform: twitter
      consumer_key: !secret twitter_API_KEY
      consumer_secret: !secret twitter_API_SECRET
      access_token: !secret twitter_ACCESS_TOKEN
      access_token_secret: !secret twitter_ACCESS_SECRET
#===============================================================
## influxdb
#===============================================================
#influxdb:
#    host: localhost
#    port: 8086
#    database: homeassistant
#    username: homeassistant
#    password: !secret influx 
#    max_retries: 3
#    default_measurement: state


recorder:
  db_url: !secret mariadb
  commit_interval: 30
  auto_purge: true
  purge_keep_days: 14
  include:
    domains:
      - sensor
      - switch
      - binary_sensor
      - climate
    entity_globs:
      - binary_sensor.*
      - sensor.dsmr_*   
      - sensor.hourly_*  
      - sensor.daily_*
      - sensor.weekly_*        
      - sensor.monthly_*  
      - sensor.yesterday_* 
      - sensor.last_*
      - sensor.average_*
  exclude:
    domains:
      - media_player
      - updater
      - automation
      - weather
      - zone
      - script
    entity_globs:
      - sensor.surh*
      - sensor.*_linkquality
      - sensor.*_battery
      - sensor.*_voltage
      - sensor.*_version
      - sensor.openweathermap_*

    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.time_date
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.time_utc
      - sensor.internet_time
      - binary_sensor.snapshot_stale
      - binary_sensor.updater
      - sensor.24v_puls_voeding_hok_linkquality
      - sensor.afzuiging_linkquality
      - sensor.bijkeuken_beweging_sensor_linkquality
      - sensor.brievenbus_linkquality
      - sensor.buiten_verlichting_voor_linkquality
      - sensor.cc2530_router_linkquality
      - sensor.douche_linkquality
      - sensor.gang_beweging_sensor_linkquality
      - sensor.hok_beweging_sensor_linkquality
      - sensor.keuken_linkquality
      - sensor.laptop_stekker_linkquality
      


logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.time_date
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.time_utc
      - sensor.internet_time
#===============================================================

