### sensor: ###
### DSMR-WS ###

- platform: mqtt
  name: "DSMR Last Update"
  state_topic: "DSMR-WS/JSON/timestamp"
  unit_of_measurement: ""
  value_template: "{{ strptime(value_json.timestamp, '%y%m%d%H%M%SW') }}"

- platform: mqtt
  name: "Energy Delivered T1"
  state_topic: "DSMR-WS/JSON/energy_delivered_tariff1" 
  unit_of_measurement: "kWh"
  value_template: '{{ value_json.energy_delivered_tariff1 | round(3) }}'

- platform: mqtt
  name: "Energy Delivered T2"
  state_topic: "DSMR-WS/JSON/energy_delivered_tariff2" 
  unit_of_measurement: "kWh"
  value_template: '{{ value_json.energy_delivered_tariff2 | round(3) }}'

- platform: mqtt
  name: "Energy Returned T1"
  state_topic: "DSMR-WS/JSON/energy_returned_tariff1" 
  unit_of_measurement: "kWh"
  value_template: '{{ value_json.energy_returned_tariff1 | round(3) }}'

- platform: mqtt
  name: "Energy Returned T2"
  state_topic: "DSMR-WS/JSON/energy_returned_tariff2" 
  unit_of_measurement: "kWh"
  value_template: '{{ value_json.energy_returned_tariff2 | round(3) }}'

- platform: mqtt
  name: "Power Delivered"
  state_topic: "DSMR-WS/JSON/power_delivered" 
  unit_of_measurement: "kW"
  value_template: '{{ value_json.power_delivered | round(3) }}'

- platform: mqtt
  name: "Power Returned"
  state_topic: "DSMR-WS/JSON/power_returned"
  unit_of_measurement: "kW"
  value_template: "{{ value_json.power_returned | round(3) }}"

- platform: mqtt
  name: "Power Delivered l1"
  state_topic: "DSMR-WS/JSON/power_delivered_l1" 
  unit_of_measurement: "Watt"
  value_template: '{{ value_json.power_delivered_l1 | round(1) }}'

- platform: mqtt
  name: "Power Returned l1"
  state_topic: "DSMR-WS/JSON/power_returned_l1"
  unit_of_measurement: "Watt"
  value_template: '{{ value_json.power_returned_l1 | round(1) }}'

- platform: mqtt
  name: "Power Returned l2"
  state_topic: "DSMR-WS/JSON/power_returned_l2"
  unit_of_measurement: "Watt"
  value_template: '{{ value_json.power_returned_l2 | round(1) }}'

- platform: mqtt
  name: "Power Returned l3"
  state_topic: "DSMR-WS/JSON/power_returned_l3"
  unit_of_measurement: "Watt"
  value_template: '{{ value_json.power_returned_l3 | round(1) }}'

- platform: mqtt
  name: "Gas Delivered"
  state_topic: "DSMR-WS/JSON/gas_delivered"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.gas_delivered | round(2) }}'