substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-2021-v1.5"
  device_description: ble scanner beneden
  friendly_name: ble-sanner-beneden
  name: ble_scanner_beneden
  
esphome:
  name: ble-scanner-207
  platform: ESP32
  board: esp32dev
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.207
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails

  ap:
    ssid: "Ble-Scanner-207 Fallback Hotspot"
    password: "xQAeDqLLO6sy"

captive_portal:
esp32_ble_tracker:

sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:9C:A4:C6"
    temperature:
      name: "ATC Temperature-c6"
    humidity:
      name: "ATC Humidity-c6"
    battery_level:
      name: "ATC Battery-Level-c6"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:B0:17:99"
    temperature:
      name: "ATC Temperature-99"
    humidity:
      name: "ATC Humidity-99"
    battery_level:
      name: "ATC Battery-Level-99"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:81:30:C4"
    temperature:
      name: "ATC Temperature-c4"
    humidity:
      name: "ATC Humidity-c4"
    battery_level:
      name: "ATC Battery-Level-c4"
  
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:7B:35:7D"
    temperature:
      name: "ATC Temperature-7d"
    humidity:
      name: "ATC Humidity-7d"
    battery_level:
      name: "ATC Battery-Level-7d"

#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline