substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-2021-v1.3"
  device_description: temperatuur sensoren op de leidingen bij de cv
  friendly_name:  cv_ketel
  name: temp_cv_ketel
  
esphome:
  name: cv-ketel-199
  platform: ESP8266
  board: esp01_1m
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip: #use adress:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.199
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cv-Ketel Fallback Hotspot"
    password: "nT63fe44xLdc"

captive_portal:
# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
dallas:
  - pin: GPIO2
sensor:
  - platform: dallas
    address: 0xCA0000070E370228
    name: "Temperature #1"
  - platform: dallas
    address:  0x660000070E477128
    name: "Temperature #2"
  - platform: dallas
    address:  0xD90000070E3AB928
    name: "Temperature #3"
  - platform: dallas
    address:  0x2D0000070E39F328
    name: "Temperature #4"


#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline