substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-2021-v1.8"
  device_description: deurbel melding
  friendly_name: deurbel-systeem
  name: deurbel-systeem
  
esphome:
  name: deurbel-191
  platform: ESP8266
  board: d1_mini
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.191
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Deurbel Fallback Hotspot"
    password: "Deurbelwifi"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


# Binary sensor representing the
# Doorbell button push.
binary_sensor:
  - platform: gpio
    id: button
    name: Doorbell Button
    pin:
      # Connected to GPIO on the ESP-01S.
      number: D5
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    
      # Only turn on the chime when it is active.
      
#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline