substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-202-v2.1"
  device_description: themperatuur hok en koelkast
  friendly_name: bier_koelkast_hok
  name: hok_temp_en_omgeving
  
esphome:
  name: hok_koelkast_omgeving-202
  platform: ESP8266
  board: esp12e
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"
    
wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.202
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails

  ap:
    ssid: "Hok Koelkast Omgeving-202"
    password: "8jHoCCkjlYQw"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
dallas:
  - pin: GPIO13 
  
sensor:
  - platform: dallas
    address:  0x1E00000758ADFE28
    name: "Hok_koelkast Temperatuur"

  - platform: dht
    model: DHT11
    pin: GPIO14
    temperature:
      name: "hok Room Temperature"
    humidity:
      name: "hok Room Humidity"
    update_interval: 60s
    
#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline