substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-2021-v1.3"
  device_description: ledstrip wit 2m 12v
  friendly_name:  ledstrip
  name: ledstrip_wit
  
esphome:
  name: led-strip-wit-209
  platform: ESP8266
  board: esp8285
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.209
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Strip-Wit-209"
    password: "h08a0BtSJhr2"

captive_portal:

light:
  - platform: monochromatic
    name: ledstrip-wit-dimmer
    output: pwm1

output:
  - platform: esp8266_pwm
    id: pwm1
    pin: GPIO12
    frequency: 1000 Hz
    
#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline 