esphome:
  name: sonoff_basic_zwembad_pomp-201
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid2
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.201
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff Basic Zwembad Pomp"
    password: "KXQiUqxQgVCZ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
ota:
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff zwembad_pomp Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff zwembad_pomp"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes