esphome:
  name: temperatuur-overkapping_204
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret ssid2
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.204
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperatuur-Overkapping 204"
    password: "5jQKEFYdGRhQ"

captive_portal:

# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
sensor:
  - platform: adc
    pin: A0
    name: "overkapping Brightness"
    update_interval: 60s
    filters:
      - multiply: 3.3
    
  - platform: dht
    model: DHT11
    pin: GPIO14
    temperature:
      name: "overkapping Temperatuur"
    humidity:
      name: "overkapping Humidity"
    update_interval: 60s