substitutions:
  time_timezone: "Europe/Amsterdam"
  version: "1.3"
  device_description: co2-vindriktning-ikea
  friendly_name:  vindriktning-co2

esphome:
  name: co2-vindriktning-ikea
  platform: ESP8266
  board: d1_mini
  
  project:
    name: "${friendly_name}.huizebruin"
    version: "${version}"

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.211
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
    
      # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning-Ikea-Co2"
    password: "WNZOyduPfzt6"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Livingroom Particulate Matter 2.5µm Concentration"
      


switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"
        
text_sensor:
  - platform: version
    name: "ESPHome Version - ${friendly_name} "
    hide_timestamp: true

  - platform: template
    name: "Esphome ${friendly_name} Version"
    update_interval: 5h
    lambda: |-
      return {"${version}"};

