substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-2021-v1.8"
  device_description: co2-vindriktning-ikea
  friendly_name:  vindriktning-co2
  name: vindriktning_c02

esphome:
  name: co2-vindriktning-ikea
  platform: ESP8266
  board: d1_mini
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.211
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
    
      # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning-Ikea-Co2"
    password: "WNZOyduPfzt6"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


captive_portal:

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "air_quality_index_vindriktning_pm2_5"
      

#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline
      
