substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "17-11-2021-v1.7"
  device_description: themperatuur lux en humanity meting in de woonkamer
  friendly_name:  woonkamer_temp_info
  name: woonkamer_temp_lux_info
  
esphome:
  name: woonkamer-esp8266-200
  platform: ESP8266
  board: nodemcu
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.200
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.2 
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 
  # Enable fallback hotspot (captive portal) in case wifi connection fails

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Woonkamer-Esp8266-200"
    password: "FdkQPSYjgCx4"

captive_portal:

# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
i2c:
  sda: GPIO04
  scl: GPIO05
  scan: True
  
sensor:
  - platform: htu21d
    temperature:
      name: "Living Room Temperature-htu21d"
    humidity:
      name: "Living Room Humidity-htu21d"
    update_interval: 60s
    address: 0x40
    
  - platform: bmp085
    temperature:
      name: "Living Room Temperature-bmp180"
    pressure:
      name: "Living Room Pressure-bmp180"
    update_interval: 60s
    address: 0x77
  
  - platform: bh1750
    name: "BH1750 Illuminance"
    
    measurement_duration: 69
    update_interval: 60s
    

#versie sensor voor in ha
text_sensor:
  - platform: template
    name: " Versie"
    icon: "mdi:label-outline"
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};
      
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline
